---
title: Short stories
---

Gothic, dark academia short stories which act as prequels to my debut novel SISTER KNIVES.

IN THE COMPANY OF THESE CORPSES - It’s 1617, there are seven bodies to be prepared for the dissection demonstration tomorrow - but weren’t there only meant to be six?

—Currently under consideration—

REST OF THEIR BONES - When the lecturer wants a particular body to dissect… you’re going to need a crowbar.

—Halloween release planned—

Teaser 200 words below



# Rest of Their Bones
### Bologna, November, 1617 AD

As I stood over the body, I recalled one of my fondest memories of my childhood. I had not yet been inducted into my mother’s winter occupation—the dissection of human remains and their meticulous reproduction in wax—and so would prowl around our modest rooms in search of medical treasures while my mother was otherwise occupied.

My favourite item was the _Catoptrum Microcosmicum_. How my mother had obtained this wondrous work of medical discovery, so recently printed, was unknown to me. But it did not signify as I pored over the delicate illustrations.

The human form, both male and female, laid out on display with layers of fragile paper cut to the outline of the strata of skin, fat, muscle, veins, and my favourite at the time, the bones. I would remove the layers one by one until I reached them, and then rebuild the little figure until he was fully formed, before starting the process again.

Like the little figures in my book, the man lying on my table did not have a name. The remains had been supplied to us from the Hospital of Death, but unlike our usual deliveries, he had not been a condemned man. Just a poor one. Much like during his life, he was not wanted in death either.
